# Generated by Django 5.2.4 on 2026-08-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='referral_credit',
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='per_word_rate',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=6),
        ),
    ]
