# Generated by Django 6.1 on 2026-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_submission_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_tier',
            field=models.CharField(choices=[('check', 'Check'), ('improve', 'Improve'), ('complete', 'Complete')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='editing_suggestions_fee',
            field=models.DecimalField(decimal_places=2, default=549.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=299.0, max_digits=10),
        ),
    ]
