# Generated by Django 6.1 on 2026-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_package_tier_and_gst_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
