# Generated by Django 5.1.7 on 2026-09-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_documents', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
